# Generated by Django 3.2 on 2021-05-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyboard', '0002_auto_20210506_1431'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
